#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libndp
Version  : 1.7
Release  : 7
URL      : https://github.com/jpirko/libndp/archive/v1.7.tar.gz
Source0  : https://github.com/jpirko/libndp/archive/v1.7.tar.gz
Summary  : Neighbour discovery library.
Group    : Development/Tools
License  : LGPL-2.1
Requires: libndp-bin
Requires: libndp-lib
Requires: libndp-license
Requires: libndp-man
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32

%description
# libndp - Library for Neighbor Discovery Protocol #
This package contains a library which provides a wrapper
for IPv6 Neighbor Discovery Protocol.  It also provides a tool
named ndptool for sending and receiving NDP messages.

%package bin
Summary: bin components for the libndp package.
Group: Binaries
Requires: libndp-license
Requires: libndp-man

%description bin
bin components for the libndp package.


%package dev
Summary: dev components for the libndp package.
Group: Development
Requires: libndp-lib
Requires: libndp-bin
Provides: libndp-devel

%description dev
dev components for the libndp package.


%package dev32
Summary: dev32 components for the libndp package.
Group: Default
Requires: libndp-lib32
Requires: libndp-bin
Requires: libndp-dev

%description dev32
dev32 components for the libndp package.


%package lib
Summary: lib components for the libndp package.
Group: Libraries
Requires: libndp-license

%description lib
lib components for the libndp package.


%package lib32
Summary: lib32 components for the libndp package.
Group: Default
Requires: libndp-license

%description lib32
lib32 components for the libndp package.


%package license
Summary: license components for the libndp package.
Group: Default

%description license
license components for the libndp package.


%package man
Summary: man components for the libndp package.
Group: Default

%description man
man components for the libndp package.


%prep
%setup -q -n libndp-1.7
pushd ..
cp -a libndp-1.7 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530280550
%autogen --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%autogen --disable-static   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1530280550
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libndp
cp COPYING %{buildroot}/usr/share/doc/libndp/COPYING
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ndptool

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libndp.so
/usr/lib64/pkgconfig/libndp.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libndp.so
/usr/lib32/pkgconfig/32libndp.pc
/usr/lib32/pkgconfig/libndp.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libndp.so.0
/usr/lib64/libndp.so.0.1.1

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libndp.so.0
/usr/lib32/libndp.so.0.1.1

%files license
%defattr(-,root,root,-)
/usr/share/doc/libndp/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man8/ndptool.8
