#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libndp
Version  : 1.6
Release  : 5
URL      : http://libndp.org/files/libndp-1.6.tar.gz
Source0  : http://libndp.org/files/libndp-1.6.tar.gz
Summary  : Neighbour discovery library.
Group    : Development/Tools
License  : LGPL-2.1
Requires: libndp-bin
Requires: libndp-lib
Requires: libndp-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32

%description
# libndp - Library for Neighbor Discovery Protocol #
This package contains a library which provides a wrapper
for IPv6 Neighbor Discovery Protocol.  It also provides a tool
named ndptool for sending and receiving NDP messages.

%package bin
Summary: bin components for the libndp package.
Group: Binaries

%description bin
bin components for the libndp package.


%package dev
Summary: dev components for the libndp package.
Group: Development
Requires: libndp-lib
Requires: libndp-bin
Provides: libndp-devel

%description dev
dev components for the libndp package.


%package dev32
Summary: dev32 components for the libndp package.
Group: Default
Requires: libndp-lib32
Requires: libndp-bin
Requires: libndp-dev

%description dev32
dev32 components for the libndp package.


%package doc
Summary: doc components for the libndp package.
Group: Documentation

%description doc
doc components for the libndp package.


%package lib
Summary: lib components for the libndp package.
Group: Libraries

%description lib
lib components for the libndp package.


%package lib32
Summary: lib32 components for the libndp package.
Group: Default

%description lib32
lib32 components for the libndp package.


%prep
%setup -q -n libndp-1.6
pushd ..
cp -a libndp-1.6 build32
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1482958929
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ndptool

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libndp.so
/usr/lib64/pkgconfig/libndp.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libndp.so
/usr/lib32/pkgconfig/32libndp.pc
/usr/lib32/pkgconfig/libndp.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libndp.so.0
/usr/lib64/libndp.so.0.1.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libndp.so.0
/usr/lib32/libndp.so.0.1.0
